export const GET_ALL_DOGS = "GET_ALL_DOGS";
export const LOADER = "LOADER";
export const GET_DOG_BY_NAME = "GET_DOG_BY_NAME";
export const GET_DOG_DETAIL = "GET_DOG_DETAIL";
export const MANAGE_ERROR = "MANAGE_ERROR";
export const GET_ALL_TEMPERAMENTS = "GET_ALL_TEMPERAMENTS";
export const FILTER_BY_TEMPERAMENTS = "FILTER_BY_TEMPERAMENTS";
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN";

export const FILTER_BY_NAME = "FILTER_BY_NAME";
export const FILTER_BY_WEIGHT = "FILTER_BY_WEIGHT";
export const POST_DOG = "POST_DOG";
export const CLEAR_DETAIL = "CLEAR_DETAIL";
export const DELETE_DOG = "DELETE_DOG";
